---
apiVersion: v1
kind: Secret
metadata:
  name: secumon-db
  namespace: secumon
type: Opaque
stringData:
  DB_HOST: "timescaledb"
  DB_PORT: "5432"
  DB_USER: "metrics_writer"
  DB_PASSWORD: "metrics_prod_pass_2026"
  DB_NAME: "metrics"

---
apiVersion: v1
kind: Secret
metadata:
  name: secumon-redis
  namespace: secumon
type: Opaque
stringData:
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"

---
apiVersion: v1
kind: Secret
metadata:
  name: secumon-jwt
  namespace: secumon
type: Opaque
stringData:
  JWT_SECRET: "secumon_jwt_secret_key_2026_production"
  JWT_ENABLED: "false"
