---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: secumon-api
  namespace: secumon
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/websocket-services: "secumon-api"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - secumon-api.dev.secuaas.com
    secretName: secumon-api-tls
  rules:
  - host: secumon-api.dev.secuaas.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: secumon-api
            port:
              number: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: secumon-grafana
  namespace: secumon
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - secumon-grafana.dev.secuaas.com
    secretName: secumon-grafana-tls
  rules:
  - host: secumon-grafana.dev.secuaas.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: grafana
            port:
              number: 3000
