apiVersion: 1

datasources:
  - name: SecuMon-TimescaleDB
    type: postgres
    access: proxy
    url: timescaledb:5432
    database: metrics
    user: metrics_writer
    secureJsonData:
      password: metrics_dev_pass
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: true
    isDefault: true
    editable: true
